const USER_ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  MEMBER: "MEMBER",
};

const TASK_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

const TASK_STATUS = {
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  IN_REVIEW: "IN_REVIEW",
  BLOCKED: "BLOCKED",
  DONE: "DONE",
};

const TASK_STATUS_TRANSITIONS = {
  [TASK_STATUS.TODO]: [
    TASK_STATUS.IN_PROGRESS,
    TASK_STATUS.BLOCKED,
  ],

  [TASK_STATUS.IN_PROGRESS]: [
    TASK_STATUS.IN_REVIEW,
    TASK_STATUS.BLOCKED,
  ],

  [TASK_STATUS.IN_REVIEW]: [
    TASK_STATUS.DONE,
    TASK_STATUS.BLOCKED,
  ],

  [TASK_STATUS.BLOCKED]: [
    TASK_STATUS.IN_PROGRESS,
  ],

  [TASK_STATUS.DONE]: [],
};


module.exports = {
  USER_ROLES,
  TASK_PRIORITY,
  TASK_STATUS,
  TASK_STATUS_TRANSITIONS,
};